### ISSUE TITLE
Invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by tomazartack** [FreedomBen/dory#64]
Hello, when running dory start, or similar commands like dory status, dory stop, where it needs docker_service, I run into this issue:

> dory start
/opt/homebrew/Cellar/dory/1.2.0/libexec/gems/dory-1.2.0/lib/dory/docker_service.rb:52:in `running?': invalid byte sequence in US-ASCII (ArgumentError)
        from /opt/homebrew/Cellar/dory/1.2.0/libexec/gems/dory-1.2.0/lib/dory/docker_service.rb:30:in `start'
        from /opt/homebrew/Cellar/dory/1.2.0/libexec/gems/dory-1.2.0/bin/dory:330:in `exec_up'
        from /opt/homebrew/Cellar/dory/1.2.0/libexec/gems/dory-1.2.0/bin/dory:43:in `up'
        from /opt/homebrew/Cellar/dory/1.2.0/libexec/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /opt/homebrew/Cellar/dory/1.2.0/libexec/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/homebrew/Cellar/dory/1.2.0/libexec/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /opt/homebrew/Cellar/dory/1.2.0/libexec/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /opt/homebrew/Cellar/dory/1.2.0/libexec/gems/dory-1.2.0/bin/dory:532:in `<top (required)>'
        from /opt/homebrew/Cellar/dory/1.2.0/libexec/bin/dory:25:in `load'
        from /opt/homebrew/Cellar/dory/1.2.0/libexec/bin/dory:25:in `<main>'

My system:
Dory: 1.2.0
Docker Engine: v20.10.22
Docker desktop: 4.16.2 (95914)
MacOS Monterey 12.5, Macbook Pro 2021, Chip Apple M1 Max

**Comment by tomazartack** [comment]
I have solved the issue, but still thought it would be nice to post it here in case somebody runs in the same problem. It only occurred when running dory commands from within Phpstorm built-in terminal.

The solution was to run dory commands from a separate Terminal app on MacOS. There it worked fine.
